name: Clear cache
on: workflow_dispatch
jobs:
  clear-cache:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
    steps:
      - uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: os-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: remove target
        shell: bash
        run: |
          rm -fr target
          mkdir target

