name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - v[0-9]*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: os-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-wasi
    - name: Cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --features integration-tests
    - run: rustup component add clippy
      if: matrix.os == 'linux'
    - uses: actions-rs/clippy-check@v1
      if: matrix.os == 'linux'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all --all-features

